House.destroy_all
Character.destroy_all

house_list = [
  ["House Arryn", "/images/arryn.jpg"],
  ["House Baratheon", "/images/baratheon.jpg"],
  ["House Bolton", "/images/bolton.jpg"],
  ["House Frey", "/images/frey.jpg"],
  ["House Greyjoy", "/images/greyjoy.jpg"],
  ["House Lannister", "/images/lannister.jpg"],
  ["House Martell", "/images/martell.jpg"],
  ["House Stark", "/images/stark.jpg"],
  ["House Targaryen", "/images/targaryen.jpg"],
  ["House Tully", "/images/tully.jpg"],
  ["House Tyrell", "/images/tyrell.jpg"]
]

house_list.each do |name, image|
  House.create(name: name, img_url: image)
end

character_list = [
  ["Robin Arryn", "Male", "/images/characters/robin.jpg", 1],
  ["Yohn Royce", "Male", "/images/characters/yohn.jpg", 1],
  ["Anya Waynwood", "Female", "/images/characters/anya.jpg", 1],
  ["Lysa Arryn", "Female", "/images/characters/lysa.jpg", 1],
  ["Davos Seaworth", "Male", "/images/characters/davos.jpg", 2],
  ["Melisandre", "Female", "/images/characters/melisandre.jpg", 2],
  ["Tommen Baratheon", "Male", "/images/characters/tommen.jpg", 2],
  ["Stannis Baratheon", "Male", "/images/characters/stannis.jpg", 2],
  ["Joffrey Baratheon", "Male", "/images/characters/joffrey.jpg", 2],
  ["Robert Baratheon", "Male", "/images/characters/robert.jpg", 2],
  ["Gendry", "Male", "/images/characters/gendry.jpg", 2],
  ["Myrcella Baratheon", "Female", "/images/characters/myrcella.jpg", 2],
  ["Selyse Florent", "Female", "/images/characters/selyse.jpg", 2],
  ["Shireen Baratheon", "Female", "/images/characters/shireen.jpg", 2],
  ["Renly Baratheon", "Male", "/images/characters/renly.jpg", 2],
  ["Salladhor Saan", "Male", "/images/characters/salladhor.jpg", 2],
  ["Matthos Seaworth", "Male", "/images/characters/matthos.jpg", 2],
  ["Maester Cressen", "Male", "/images/characters/cressen.jpg", 2],
  ["Ramsay Bolton", "Male", "/images/characters/ramsay.jpg", 3],
  ["Roose Bolton", "Male", "/images/characters/roose.jpg", 3],
  ["Robett Glover", "Male", "/images/characters/robett.jpg", 3],
  ['"Fat" Walda Bolton', "Female", "/images/characters/walda.jpg", 3],
  ["Maester Wolkan", "Male", "/images/characters/wolkan.jpg", 3],
  ["Harald Karstark", "Male", "/images/characters/harald.jpg", 3],
  ["Jon Umber", "Male", "/images/characters/small-jon.jpg", 3],
  ["Myranda", "Female", "/images/characters/myranda.jpg", 3],
  ["Locke", "Male", "/images/characters/locke.jpg", 3],
  ["Walder Frey", "Male", "/images/characters/walder.jpg", 4],
  ['"Lame" Lothar Frey', "Male", "/images/characters/lothar.jpg", 4],
  ['"Black" Walder Rivers', "Male", "/images/characters/black-walder.jpg", 4],
  ["Theon Greyjoy", "Male", "/images/characters/theon.jpg", 5],
  ["Yara Greyjoy", "Female", "/images/characters/yara.jpg", 5],
  ["Euron Greyjoy", "Male", "/images/characters/euron.jpg", 5],
  ["Aeron Greyjoy", "Male", "/images/characters/aeron.jpg", 5],
  ["Balon Greyjoy", "Male", "/images/characters/balon.jpg", 5],
  ["Dagmer Cleftjaw", "Male", "/images/characters/dagmer.jpg", 5],
  ["Lorren", "Male", "/images/characters/lorren.jpg", 5],
  ["Tyrion Lannister", "Male", "/images/characters/tyrion.jpg", 6],
  ["Jaime Lannister", "Male", "/images/characters/jaime.jpg", 6],
  ["Cersei Lannister", "Female", "/images/characters/cersei.jpg", 6],
  ["Tywin Lannister", "Male", "/images/characters/tywin.jpg", 6],
  ["Gregor Clegane", "Male", "/images/characters/gregor.jpg", 6],
  ["Kevan Lannister", "Male", "/images/characters/kevan.jpg", 6],
  ["Lancel Lannister", "Male", "/images/characters/lancel.jpg", 6],
  ["Polliver", "Male", "/images/characters/polliver.jpg", 6],
  ["Alton Lannister", "Male", "/images/characters/alton.jpg", 6],
  ["Amory Lorch", "Male", "/images/characters/amory.jpg", 6],
  ["Nymeria Sand", "Female", "/images/characters/nymeria.jpg", 7],
  ["Ellaria Sand", "Female", "/images/characters/ellaria.jpg", 7],
  ["Obara Sand", "Female", "/images/characters/obara.jpg", 7],
  ["Tyene Sand", "Female", "/images/characters/tyene.jpg", 7],
  ["Trystane Martell", "Male", "/images/characters/trystane.jpg", 7],
  ["Doran Martell", "Male", "/images/characters/doran.jpg", 7],
  ["Areo Hotah", "Male", "/images/characters/areo.jpg", 7],
  ["Oberyn Martell", "Male", "/images/characters/oberyn.jpg", 7],
  ["John Snow", "Male", "/images/characters/johnsnow.jpg", 8],
  ["Sansa Stark", "Female", "/images/characters/sansa.jpg", 8],
  ["Arya Stark", "Female", "/images/characters/arya.jpg", 8],
  ["Bran Stark", "Male", "/images/characters/bran.jpg", 8],
  ["Catelyn Stark", "Female", "/images/characters/catelyn.jpg", 8],
  ["Robb Stark", "Male", "/images/characters/robb.jpg", 8],
  ["Talisa Stark", "Female", "/images/characters/talisa.jpg", 8],
  ["Ned Stark", "Male", "/images/characters/ned.jpg", 8],
  ["Meera Reed", "Female", "/images/characters/meera.jpg", 8],
  ["Lyanna Mormont", "Female", "/images/characters/lyanna.jpg", 8],
  ["Rickon Stark", "Male", "/images/characters/rickon.jpg", 8],
  ["Hodor", "Male", "/images/characters/hodor.jpg", 8],
  ["Osha", "Female", "/images/characters/osha.jpg", 8],
  ["Jojen Reed", "Male", "/images/characters/jojen.jpg", 8],
  ["Rickard Karstark", "Male", "/images/characters/rickard.jpg", 8],
  ["Maester Luwin", "Male", "/images/characters/luwin.jpg", 8],
  ["Rodrik Cassel", "Male", "/images/characters/rodrik.jpg", 8],
  ["Jory Cassel", "Male", "/images/characters/jory.jpg", 8],
  ["Septa Mordane", "Female", "/images/characters/septa.jpg", 8],
  ["Old Nan", "Female", "/images/characters/nan.jpg", 8],
  ["Jon Umber (Greatjon)", "Male", "/images/characters/jon.jpg", 8],
  ["Daenerys Targaryen", "Female", "/images/characters/daenerys.jpg", 9],
  ["Viserys Targaryen", "Male", "/images/characters/viserys.jpg", 9],
  ["Grey Worm", "Male", "/images/characters/grey.jpg", 9],
  ["Barristan Selmy", "Male", "/images/characters/barristan.jpg", 9],
  ["Hizdahr zo Loraq", "Male", "/images/characters/hizdahr.jpg", 9],
  ["Mossador", "Male", "/images/characters/mossador.jpg", 9],
  ["Kovarro", "Male", "/images/characters/kovarro.jpg", 9],
  ["Doreah", "Female", "/images/characters/doreah.jpg", 9],
  ["Irri", "Female", "/images/characters/irri.jpg", 9],
  ["Rakharo", "Male", "/images/characters/rakharo.jpg", 9],
  ["Edmure Tully", "Male", "/images/characters/edmure.jpg", 10],
  ["Brynden Tully", "Male", "/images/characters/brynden.jpg", 10],
  ["Roslin Frey", "Female", "/images/characters/roslin.jpg", 10],
  ["Margaery Tyrell", "Female", "/images/characters/margaery.jpg", 11],
  ["Olenna Tyrell", "Female", "/images/characters/olenna.jpg", 11],
  ["Mace Tyrell", "Male", "/images/characters/mace.jpg", 11],
  ["Loras Tyrell", "Male", "/images/characters/loras.jpg", 11],
  ["Randyll Tarly", "Male", "/images/characters/randyll.jpg", 11],
  ["Melessa Tarly", "Female", "/images/characters/melessa.jpg", 11],
  ["Talla Tarly", "Female", "/images/characters/talla.jpg", 11],
  ["Dickon Tarly", "Male", "/images/characters/dickon.jpg", 11]
]

character_list.each do |name, gender, image, house|
  Character.create(name: name, gender: gender, img_url: image, house_id: house)
end
